name: Build & Release

on:
  push:
    tags:
      - 'v*'  # 匹配发布版本号
  workflow_dispatch:
    inputs:
      build_type:
        description: 构建类型
        required: true
        default: all
        type: choice
        options:
          - all
          - single
      branch:
        description: 单分支名称（如1.21.10）
        required: false
        default: ''

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.branches.outputs.branches }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - id: branches
        run: |
          branches=$(git branch -r | grep -v '\->' | sed 's/origin\///' | sort -Vu | jq -R . | jq -cs .)
          echo "branches=$branches" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.prepare.branches) }}
      fail-fast: false
    continue-on-error: true

    steps:
      - name: 过滤分支
        if: |
          (github.event.inputs.build_type == 'single' && github.event.inputs.branch == matrix.branch) ||
          (github.event.inputs.build_type == 'all') ||
          (github.event_name == 'push')
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build --no-daemon

      - name: 获取版本号
        id: version
        run: |
          mod_ver=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          mc_ver=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)
          echo "mod=$mod_ver" >> $GITHUB_OUTPUT
          echo "mc=$mc_ver" >> $GITHUB_OUTPUT

      - name: 重命名 JAR
        run: |
          cd build/libs
          rm -f *-sources.jar
          mv *.jar AdvancedScoreboard-fabric-${{ steps.version.outputs.mod }}-${{ steps.version.outputs.mc }}.jar

      - name: 上传 Jar
        uses: upload-artifact@v4
        with:
          name: jars-${{ matrix.branch }}
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 下载所有 Jar
        uses: download-artifact@v4
        with:
          path: outputs
          pattern: jars-*
          merge-multiple: true

      - name: 获取发布版本号
        run: echo "RELEASE_VER=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_VER }}       # 标题 = 1.0
          tag_name: ${{ env.RELEASE_VER }}    # Tag = 1.0
          files: outputs/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}